- platform: mqtt
  name: "Ogrzewanie"
  modes: 
    - "auto"
    - "heat"
    - "cool"
    - "off"
  mode_state_template: >-
      {% set values = { 'auto':'auto', 'on':'heat', 'night':'cool', 'summer':'off'} %}
      {{ values[value] if value in values.keys() else 'off' }}
  mode_command_topic: "convert/modeset"
  mode_state_topic:  "ebusd/470/Hc1OPMode"
  temperature_state_topic: "ebusd/470/DisplayedHc1RoomTempDesired"
  temperature_low_state_topic: "ebusd/470/Hc1NightTemp"
  temperature_high_state_topic: "ebusd/470/Hc1DayTemp"
  temperature_low_command_topic: "ebusd/470/Hc1NightTemp/set"
  temperature_high_command_topic: "ebusd/470/Hc1DayTemp/set"
  current_temperature_topic: "ebusd/470/DisplayedHc1RoomTempDesired"
- platform: mqtt
  name: "Ciepła woda"
  temperature_state_topic: "ebusd/470/HwcActualTempDesired"
  temperature_command_topic: "ebusd/470/Hc1NightTemp/set"
  current_temperature_topic: "ebusd/bai/HwcTemp"
