# Ogrzewanie CO i CWU

- platform: mqtt
  name: "Ogrzewanie"
  modes: 
    - "auto"
    - "heat"
    - "cool"
    - "off"
  mode_state_template: >-
      {% set values = { 'auto':'auto', 'day':'heat', 'night':'cool', 'off':'off'} %}
      {{ values[value] if value in values.keys() else 'off' }}
  mode_command_topic: "convert/modeset"
  mode_state_topic:  "ebusd/700/OpMode"
  temperature_state_topic: "ebusd/700/z1RoomTemp"
  temperature_low_state_topic: "ebusd/700/z1NightTemp"
  temperature_high_state_topic: "ebusd/700/z1DayTemp"
  temperature_low_command_topic: "ebusd/700/z1NightTemp/set"
  temperature_high_command_topic: "ebusd/700/z1DayTemp/set"
  current_temperature_topic: "ebusd/700/z1RoomTemp"

- platform: mqtt
  name: "Ciepła woda"
  min_temp: 35
  max_temp: 65
  modes: 
    - "auto"
    - "heat"
    - "off"
  mode_state_template: >-
      {% set values = { 'auto':'auto', 'day':'heat', 'off':'off'} %}
      {{ values[value] if value in values.keys() else 'off' }}
  mode_command_topic: "convert/Hwcmodeset"
  mode_state_topic:  "ebusd/700/HwcOpMode"      
  temperature_state_topic: "ebusd/700/HwcTempDesired"
  temperature_command_topic: "ebusd/700/HwcTempDesired/set"
  current_temperature_topic: "ebusd/bai/StorageTemp"