- alias: Set Central Heating Set Night Temperature
  initial_state: on
  trigger:
    - platform: state
      entity_id: input_number.central_heating_set_night_temp
  action:
    service: mqtt.publish
    data_template:
      topic: "ebusd/720/Hc1NightTemp/set"
      payload: "{{ states.input_number.central_heating_set_night_temp.state | int }}"

- alias: Get Central Heating Set Night Temperature
  initial_state: on
  trigger:
    - platform: mqtt
      topic: "ebusd/720/Hc1NightTemp"
  action:
    service: input_number.set_value
    data_template:
      entity_id: input_number.central_heating_set_night_temp
      value: "{{ trigger.payload | int }}"
