- alias: Set Hot Water Temperature Desired
  initial_state: on
  trigger:
    - platform: state
      entity_id: input_number.hot_water_temp_desired
  action:
    service: mqtt.publish
    data_template:
      topic: "ebusd/720/HwcTempDesired/set"
      payload: "{{ states.input_number.hot_water_temp_desired.state | int }}"

- alias: Get Hot Water Temperature Desired
  initial_state: on
  trigger:
    - platform: mqtt
      topic: "ebusd/720/HwcTempDesired"
  action:
    service: input_number.set_value
    data_template:
      entity_id: input_number.hot_water_temp_desired
      value: "{{ trigger.payload | int }}"
